#ifndef SPECTRUM_VERSION_HPP
#define SPECTRUM_VERSION_HPP

#define SPECTRUM_VERSION_MAJOR 3
#define SPECTRUM_VERSION_MINOR 0
#define SPECTRUM_VERSION_PATCH 0
#define SPECTRUM_VERSION "3.0.0"

#endif // SPECTRUM_VERSION_HPP 
